-d /home/gindrus/fpga/Costas_v3/impl/gwsynthesis/Costas_v3.vg
-p GW2AR-18C-QFN88-8
-pn GW2AR-LV18QN88C8/I7
-cst /home/gindrus/fpga/Costas_v3/src/constraints.cst
-cfg /home/gindrus/fpga/Costas_v3/impl/pnr/device.cfg
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
